sonar.projectKey=gourabd1ms_py-monorepo_service_b
sonar.organization=gourabd1ms
sonar.projectName=service_b
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.9,3.10,3.11
sonar.python.coverage.reportPaths=coverage.xml
